(define (make-account balance secret-password)
  (let ((unauthorized 0))
    (define (reset-unauthorized) (set! unauthorized 0))
    (define (incorrect-password . args) 
      (set! unauthorized (+ unauthorized 1))
      (if (> unauthorized 7)
        (begin (reset-unauthorized) (call-the-cops)))
      "Incorrect password")
    (define (withdraw amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount)) balance)
          "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount)) balance)
    (define (dispatch password method)
      (if (eq? secret-password password)
        (begin
          (reset-unauthorized)
          (cond ((eq? method 'withdraw) withdraw)
                ((eq? method 'deposit) deposit)
                (else (error "Unknown request -- MAKE-ACCOUNT" m))))
        incorrect-password))
    dispatch))

(define (call-the-cops) (display " !!CALLING THE COPS!! "))
