(define (make-account balance secret-password)
  (define (incorrect-password . args) "Incorrect password")
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount)) balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount)) balance)
  (define (check-password password) (eq? secret-password password))
  (define (dispatch password method)
      (cond ((eq? method 'check-password) (lambda () (check-password password)))
            ((not (check-password password)) incorrect-password)
            ((eq? method 'withdraw) withdraw)
            ((eq? method 'deposit) deposit)
            (else (error "Unknown request -- MAKE-ACCOUNT" m))))
  dispatch)

(define (make-joint account secret-password new-secret-password)
  (if ((account secret-password 'check-password))
    (lambda (password method)
      (if (eq? new-secret-password password)
        (account secret-password method)
        (lambda args "Incorrect password")))
    (error "Incorrect initial password")))
