(define (make-account balance)
  (let ((init-balance balance))
    (define (withdraw amount)
      (set! balance (- balance amount)) balance)
    (define (deposit amount)
      (set! balance (+ balance amount)) balance)
    (define (get-balance) balance)
    (define (get-init-balance) init-balance)
    (define (dispatch msg)
      (cond
        ((eq? msg 'init-balance) get-init-balance)
        ((eq? msg 'balance) get-balance)
        ((eq? msg 'withdraw) withdraw)
        ((eq? msg 'deposit) deposit)))
    dispatch))

(define (make-account init-amount)
  (let ((balance init-amount))
    (define (withdraw amount)
      (set! balance (- balance amount)) balance)
    (define (deposit amount)
      (set! balance (+ balance amount)) balance)
    (define (get-balance) balance)
    (define (init-balance) init-amount)
    (define (dispatch msg)
      (cond
        ((eq? msg 'init-balance) init-balance)
        ((eq? msg 'balance) get-balance)
        ((eq? msg 'withdraw) withdraw)
        ((eq? msg 'deposit) deposit)))
    dispatch))
