(define (make-account balance)
  (let ((transactions '()))
    (define (add-transaction type amount)
      (set! transactions (append transactions (list (list type amount)))))
    (define (withdraw amount)
      (set! balance (- balance amount))
      (add-transaction 'withdraw amount)
      balance)
    (define (deposit amount)
      (set! balance (+ balance amount))
      (add-transaction 'deposit amount)
      balance)
    (define (dispatch msg)
      (cond
        ((eq? msg 'transactions) (lambda () transactions))
        ((eq? msg 'withdraw) withdraw)
        ((eq? msg 'deposit) deposit)))
    dispatch))
