(define sample-emails
  (list (make-kv-pair 'sample-emails (list "cs61a-tb" "cs61a-tc" "mapreduce" "mapreduce is great! lucky students"))
	(make-kv-pair 'sample-emails (list "bot1337" "cs61a-ta" "free ipod now!" "buy herbal ipod enhancer"))
	(make-kv-pair 'sample-emails (list "bot1338" "cs61a-tf" "free ipod now!" "buy herbal ipod enhancer"))
	(make-kv-pair 'sample-emails (list "cs61a-tf" "cs61a-te" "jokes" "so this bear walks into a bar..."))
	(make-kv-pair 'sample-emails (list "bot1339" "cs61a-te" "free ipod now!" "buy herbal ipod enhancer"))
	(make-kv-pair 'sample-emails (list "cs61a-af" "cs61a-ag" "proj4" "help! it's not working!"))
	(make-kv-pair 'sample-emails (list "cs61a-af" "cs61a-ta" "proj4" "i get a problem with okay"))
	(make-kv-pair 'sample-emails (list "cs61a-ta" "cs61a-af" "Re: proj4" "did you forget to return =no-value= ?"))
	(make-kv-pair 'sample-emails (list "cs61a-af" "cs61a-ta" "Re: Re: proj4" "oh wow! no i didn't. Thanks! What a smart TA"))
	(make-kv-pair 'sample-emails (list "bot1340" "cs61a-ta" "free ipod now!" "buy herbal ipod enhancer"))
	(make-kv-pair 'sample-emails (list "cs61c-cs" "cs61a-fw" "have you experienced Zelda on Xbox?" "It's so fun! I fully endorse this product and/or services!"))
	(make-kv-pair 'sample-emails (list "cs61c-ug" "cs61c-dz" "lunch on Thursday the 57 of May" "or will you still be working on proj4?"))
	(make-kv-pair 'sample-emails (list "bot8431" "cs61c-tm" "Please finalise" "haha! buy our stuff!"))
	(make-kv-pair 'sample-emails (list "bot1739" "cs61c-xy" "Hot tip: buy SCOX" "haha! buy our stuff!"))
	(make-kv-pair 'sample-emails (list "cs61b-eu" "cs61b-we" "I think cs61b-fm is curmudgeonous" "do you think they like me?"))
	(make-kv-pair 'sample-emails (list "bot6246" "cs61b-ly" "Christmas special!" "haha! buy our stuff!"))
	(make-kv-pair 'sample-emails (list "bot8891" "cs61a-tb" "You've already been approved!" "haha! buy our stuff!"))
	(make-kv-pair 'sample-emails (list "bot9841" "cs61a-lg" "Dating, 15 messages for you, Olga" "haha! buy our stuff!"))
	(make-kv-pair 'sample-emails (list "bot5864" "cs61a-dj" "h3rbal 3nhancements" "haha! buy our stuff!"))
	(make-kv-pair 'sample-emails (list "cs61a-ei" "cs61b-qn" "breakfast on Tuesday the 05 of February" "or will you still be working on proj4?"))
	(make-kv-pair 'sample-emails (list "bot8148" "cs61c-yi" "Thank you for request." "haha! buy our stuff!"))
	(make-kv-pair 'sample-emails (list "bot0748" "cs61c-nz" "Christmas special!" "haha! buy our stuff!"))
	(make-kv-pair 'sample-emails (list "bot2150" "cs61c-mm" "You've already been approved!" "haha! buy our stuff!"))
	(make-kv-pair 'sample-emails (list "bot5865" "cs61a-de" "h3rbal 3nhancements" "haha! buy our stuff!"))
	(make-kv-pair 'sample-emails (list "bot8801" "cs61a-uc" "Please finalise" "haha! buy our stuff!"))
	(make-kv-pair 'sample-emails (list "bot2218" "cs61a-ip" "h3rbal 3nhancements" "haha! buy our stuff!"))
	(make-kv-pair 'sample-emails (list "bot4735" "cs61a-xd" "Hot tip: buy SCOX" "haha! buy our stuff!"))
	(make-kv-pair 'sample-emails (list "bot3294" "cs61b-al" "News" "haha! buy our stuff!"))
	(make-kv-pair 'sample-emails (list "bot5866" "cs61a-dq" "h3rbal 3nhancements" "haha! buy our stuff!"))
	(make-kv-pair 'sample-emails (list "cs61a-hx" "cs61a-pz" "I think cs61a-np is angsty" "so watch out"))))
